version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "docker"
    directory: "/apps/client"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/apps/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
