services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: threats-client
    restart: unless-stopped
    ports:
      - '8080:8080'

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: threats-server
    restart: unless-stopped
    network_mode: service:client
