name: Checks

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --prefer-offline
      - run: npm run checkformat -ws --if-present
      - run: npm run build -w @eop/shared
      - run: npm run lint -ws --if-present
      - run: npm run build -ws --if-present
      - run: npm test -ws --if-present
